//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puerta
    {
        public int Puerta1 { get; set; }
        public string PuertaDescripcion { get; set; }
        public int EdificioID { get; set; }
        public int PisoID { get; set; }
    }
}
