//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuarioID { get; set; }
        public string UsuarioUsuario { get; set; }
        public string Password { get; set; }
        public int EstatusID { get; set; }
        public int Edad { get; set; }
        public string Email { get; set; }
    
        public virtual Estatus Estatus { get; set; }
    }
}
